name: Deploy to GKE

on:
#   push:
#     branches: ["main"]

  workflow_dispatch: 
    inputs: 
      docker_image: 
        description: 'Provide docker repo'
        required: true
        default: ''

      image_tag: 
        description: 'Provide image tag'
        required: true
        default: ''


jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set GCP Project
      run: gcloud config set project zippy-folio-424123-e6

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials cluster-1 --zone us-central1-c 

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy
      run: |
        helm upgrade --install my-release ./hello --set repository.image=${{ inputs.docker_image }} --set repository.tag=${{ inputs.image_tag }}
        
       
      